# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aBM0amGN54BUD7RueZHuzVGevBfzVPUX
"""

def media(numeros):
  soma = sum(numeros)
  media= soma / len(numeros)
  return media